name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get token
        id: get-token
        uses: topmonks/app-auth-action@master
        with:
          appId: ${{ secrets.PROJECTS_AND_ISSUES_APP_ID }}
          appPrivateKey: ${{ secrets.PROJECTS_AND_ISSUES_APP_PRIVATE_KEY }}
      - name: Add issue to project
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/topmonks/projects/11
          github-token: ${{ steps.get-token.outputs.token }}
