name: Mark closed issues as "to release"

on:
  issues:
    types:
      - closed

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get-token
        uses: topmonks/app-auth-action@v1
        with:
          appId: ${{ secrets.PROJECTS_AND_ISSUES_APP_ID }}
          appPrivateKey: ${{ secrets.PROJECTS_AND_ISSUES_APP_PRIVATE_KEY }}
      - name: Move issue to column
        uses: alex-page/github-project-automation-plus@v0.8.2
        with:
          project: Calamar
          project-url: https://github.com/orgs/topmonks/projects/11
          column: ${{ github.event.issue.state_reason == 'not_planned' && 'Done' || 'To Release' }}
          repo-token: ${{ steps.get-token.outputs.token }}
