name: Test & Deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Current timestamp
        uses: ./.github/actions/now
      - name: Build
        env:
          REACT_APP_COMMIT_SHA: ${{ github.sha }}
          REACT_APP_BUILD_TIMESTAMP: ${{ env.NOW }}
          REACT_APP_ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_CLIENT_ACCESS_TOKEN }}
          CI: false
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build/
